PRAGMA user_version = 1;
DROP TABLE IF EXISTS "search_index";
DROP TABLE IF EXISTS "favourites";
DROP TABLE IF EXISTS "file_history";
DROP TABLE IF EXISTS "tagged_files";
DROP TABLE IF EXISTS "tags";
DROP TABLE IF EXISTS "file_permissions";
DROP TABLE IF EXISTS "files";
DROP TABLE IF EXISTS "mountpoints";
DROP TABLE IF EXISTS "users_in_groups";
DROP TABLE IF EXISTS "groups";
DROP TABLE IF EXISTS "logins";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "ci_sessions";
CREATE TABLE "ci_sessions"("id" TEXT PRIMARY KEY NOT NULL,"ip_address" TEXT NOT NULL,"timestamp" INTEGER DEFAULT 0 NOT NULL,"data" TEXT DEFAULT '' NOT NULL);
CREATE INDEX "ci_sessions_timestamp" ON "ci_sessions"("timestamp");
CREATE TABLE "users"("id" INTEGER PRIMARY KEY NOT NULL,"username" TEXT NOT NULL UNIQUE,"password" TEXT,"type" INTEGER NOT NULL,"full_name" TEXT,"last_password_change" INTEGER,"settings" TEXT);
CREATE TABLE "logins"("id" INTEGER PRIMARY KEY NOT NULL,"user_id" INTEGER NOT NULL REFERENCES "users","client_addr" TEXT,"user_agent" TEXT"login_time" INTEGER NOT NULL DEFAULT(STRFTIME('%s', 'now')),"last_used" INTEGER NOT NULL);
CREATE TABLE "groups"("id" INTEGER PRIMARY KEY NOT NULL,"name" TEXT NOT NULL UNIQUE);
CREATE TABLE "users_in_groups"("user_id" INTEGER NOT NULL,"group_id" INTEGER NOT NULL,UNIQUE("user_id", "group_id"));
CREATE TABLE "mountpoints"("id" INTEGER PRIMARY KEY NOT NULL,"destination_path" TEXT NOT NULL UNIQUE,"driver" TEXT NOT NULL,"driver_options" TEXT);
CREATE TABLE "files"("id" INTEGER PRIMARY KEY NOT NULL,"mountpoint_id" INTEGER NOT NULL REFERENCES "mountpoints","path_in_mountpoint" TEXT NOT NULL,"display_name" TEXT"type" INTEGER NOT NULL DEFAULT 0,"mountpoint_driver_info" TEXT NOT NULL,UNIQUE("mountpoint_id", "path_in_mountpoint"));
CREATE TABLE "file_permissions"("id" INTEGER PRIMARY KEY NOT NULL,"file_id" INTEGER NOT NULL REFERENCES "files","group_id" INTEGER NOT NULL REFERENCES "groups","owner_user_id" INTEGER REFERENCES "users","read" INTEGER NOT NULL,"write" INTEGER NOT NULL,"share" INTEGER NOT NULL,"expires" INTEGER);
CREATE TABLE "tags"("id" INTEGER PRIMARY KEY NOT NULL,"name" TEXT NOT NULL UNIQUE,"description" TEXT);
CREATE TABLE "tagged_files"("file_id" INTEGER NOT NULL REFERENCES "files","tag_id" INTEGER NOT NULL REFERENCES "tags",PRIMARY KEY("file_id", "tag_id"));
CREATE TABLE "file_history"("id" INTEGER PRIMARY KEY,"user_id" INTEGER NOT NULL REFERENCES "users","file_path" TEXT NOT NULL,"timestamp" INTEGER NOT NULL DEFAULT(STRFTIME('%s', 'now')),"action" TEXT NOT NULL);
CREATE TABLE "favourites"("id" INTEGER PRIMARY KEY,"user_id" INTEGER NOT NULL REFERENCES "users","file_path" TEXT NOT NULL,"sort_order" INTEGER NOT NULL);
CREATE TABLE "search_index"("id" INTEGER PRIMARY KEY NOT NULL,"file_path" TEXT NOT NULL,"keyword" TEXT NOT NULL,"type" TEXT,"mtime" INTEGER,"size" INTEGER,"last_indexed" INTEGER NOT NULL DEFAULT(STRFTIME('%s', 'now')));
CREATE INDEX "search_index_file_path" ON "search_index"("file_path");
CREATE INDEX "search_index_keyword" ON "search_index"("keyword");
CREATE INDEX "search_index_type" ON "search_index"("type");
CREATE INDEX "search_index_mtime" ON "search_index"("mtime");
CREATE INDEX "search_index_size" ON "search_index"("size");
CREATE INDEX "search_index_last_indexed" ON "search_index"("last_indexed");